:default: &DEFAULT
  :easy_options:
    :timeout: 15
    :headers:
      :user-agent: usasearch

  :multi_options:
    :max_connects: 8

:throttled:
  <<: *DEFAULT
  :multi_options:
    :max_connects: 3
